export const ErrorCodes = {
  // Auth
  AUTH_INVALID_CREDENTIALS: 'AUTH_INVALID_CREDENTIALS',
  AUTH_INVALID_PASSWORD: 'AUTH_INVALID_PASSWORD',
  AUTH_ACCOUNT_LOCKED: 'AUTH_ACCOUNT_LOCKED',
  AUTH_ACCOUNT_SUSPENDED: 'AUTH_ACCOUNT_SUSPENDED',
  AUTH_UNAUTHORIZED: 'AUTH_UNAUTHORIZED',
  AUTH_FORBIDDEN: 'AUTH_FORBIDDEN',
  AUTH_TOKEN_EXPIRED: 'AUTH_TOKEN_EXPIRED',
  AUTH_TOKEN_INVALID: 'AUTH_TOKEN_INVALID',
  AUTH_TOKEN_REUSE: 'AUTH_TOKEN_REUSE',
  AUTH_SESSION_EXPIRED: 'AUTH_SESSION_EXPIRED',
  AUTH_PORTAL_MISMATCH: 'AUTH_PORTAL_MISMATCH',

  // OTP
  AUTH_OTP_EXPIRED: 'AUTH_OTP_EXPIRED',
  AUTH_OTP_INVALID: 'AUTH_OTP_INVALID',
  AUTH_OTP_MAX_ATTEMPTS: 'AUTH_OTP_MAX_ATTEMPTS',
  AUTH_OTP_COOLDOWN: 'AUTH_OTP_COOLDOWN',
  AUTH_OTP_ALREADY_USED: 'AUTH_OTP_ALREADY_USED',

  // Verification
  AUTH_VERIFICATION_EXPIRED: 'AUTH_VERIFICATION_EXPIRED',

  // Registration
  AUTH_EMAIL_EXISTS: 'AUTH_EMAIL_EXISTS',
  AUTH_PHONE_EXISTS: 'AUTH_PHONE_EXISTS',
  AUTH_REGISTRATION_SESSION_INVALID: 'AUTH_REGISTRATION_SESSION_INVALID',

  // Reset
  AUTH_RESET_SESSION_INVALID: 'AUTH_RESET_SESSION_INVALID',

  // Validation
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  VALIDATION_REQUIRED: 'VALIDATION_REQUIRED',
  VALIDATION_INVALID_EMAIL: 'VALIDATION_INVALID_EMAIL',
  VALIDATION_INVALID_PHONE: 'VALIDATION_INVALID_PHONE',
  VALIDATION_PASSWORD_WEAK: 'VALIDATION_PASSWORD_WEAK',

  // Account
  ACCOUNT_NOT_FOUND: 'ACCOUNT_NOT_FOUND',
  ACCOUNT_SUSPENDED: 'ACCOUNT_SUSPENDED',
  ACCOUNT_ALREADY_SUSPENDED: 'ACCOUNT_ALREADY_SUSPENDED',
  ACCOUNT_ALREADY_ACTIVE: 'ACCOUNT_ALREADY_ACTIVE',

  // Rate Limit
  RATE_LIMIT_EXCEEDED: 'RATE_LIMIT_EXCEEDED',

  // Upload
  UPLOAD_NOT_FOUND: 'UPLOAD_NOT_FOUND',
  UPLOAD_INVALID_TYPE: 'UPLOAD_INVALID_TYPE',
  UPLOAD_TOO_LARGE: 'UPLOAD_TOO_LARGE',
  UPLOAD_ACTIVE: 'UPLOAD_ACTIVE',
  UPLOAD_DELETED: 'UPLOAD_DELETED',
  UPLOAD_INVALID_STATUS: 'UPLOAD_INVALID_STATUS',

  // Profile
  PROFILE_NOT_FOUND: 'PROFILE_NOT_FOUND',
  PROFILE_ALREADY_ACTIVE: 'PROFILE_ALREADY_ACTIVE',
  PROFILE_MISSING_BASIC: 'PROFILE_MISSING_BASIC',
  PROFILE_MISSING_COMMUNITY: 'PROFILE_MISSING_COMMUNITY',
  PROFILE_MISSING_PHOTO: 'PROFILE_MISSING_PHOTO',
  PROFILE_MISSING_DEFAULT_TRANSLATION: 'PROFILE_MISSING_DEFAULT_TRANSLATION',
  PROFILE_ALREADY_SUBMITTED: 'PROFILE_ALREADY_SUBMITTED',
  PROFILE_REJECTED: 'PROFILE_REJECTED',
  PROFILE_WRONG_STATUS: 'PROFILE_WRONG_STATUS',
  PROFILE_NAME_INVALID: 'PROFILE_NAME_INVALID',

  // Shortlist
  SHORTLIST_OWN_PROFILE: 'SHORTLIST_OWN_PROFILE',

  // Membership
  MEMBERSHIP_PLAN_NOT_FOUND: 'MEMBERSHIP_PLAN_NOT_FOUND',
  MEMBERSHIP_PLAN_INACTIVE: 'MEMBERSHIP_PLAN_INACTIVE',
  MEMBERSHIP_QUOTA_EXCEEDED: 'MEMBERSHIP_QUOTA_EXCEEDED',
  MEMBERSHIP_SLOT_LIMIT_REACHED: 'MEMBERSHIP_SLOT_LIMIT_REACHED',
  MEMBERSHIP_SHORTLIST_LIMIT_REACHED: 'MEMBERSHIP_SHORTLIST_LIMIT_REACHED',
  MEMBERSHIP_PREMIUM_REQUIRED: 'MEMBERSHIP_PREMIUM_REQUIRED',

  // General
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  NOT_FOUND: 'NOT_FOUND',
} as const;
