export const ErrorCodes = {
  // Auth
  AUTH_INVALID_CREDENTIALS: 'AUTH_INVALID_CREDENTIALS',
  AUTH_INVALID_PASSWORD: 'AUTH_INVALID_PASSWORD',
  AUTH_ACCOUNT_LOCKED: 'AUTH_ACCOUNT_LOCKED',
  AUTH_ACCOUNT_SUSPENDED: 'AUTH_ACCOUNT_SUSPENDED',
  AUTH_UNAUTHORIZED: 'AUTH_UNAUTHORIZED',
  AUTH_FORBIDDEN: 'AUTH_FORBIDDEN',
  AUTH_TOKEN_EXPIRED: 'AUTH_TOKEN_EXPIRED',
  AUTH_TOKEN_INVALID: 'AUTH_TOKEN_INVALID',
  AUTH_TOKEN_REUSE: 'AUTH_TOKEN_REUSE',
  AUTH_SESSION_EXPIRED: 'AUTH_SESSION_EXPIRED',
  AUTH_PORTAL_MISMATCH: 'AUTH_PORTAL_MISMATCH',

  // OTP
  AUTH_OTP_EXPIRED: 'AUTH_OTP_EXPIRED',
  AUTH_OTP_INVALID: 'AUTH_OTP_INVALID',
  AUTH_OTP_MAX_ATTEMPTS: 'AUTH_OTP_MAX_ATTEMPTS',
  AUTH_OTP_COOLDOWN: 'AUTH_OTP_COOLDOWN',
  AUTH_OTP_ALREADY_USED: 'AUTH_OTP_ALREADY_USED',

  // Verification
  AUTH_VERIFICATION_EXPIRED: 'AUTH_VERIFICATION_EXPIRED',

  // Registration
  AUTH_EMAIL_EXISTS: 'AUTH_EMAIL_EXISTS',
  AUTH_PHONE_EXISTS: 'AUTH_PHONE_EXISTS',
  AUTH_REGISTRATION_SESSION_INVALID: 'AUTH_REGISTRATION_SESSION_INVALID',

  // Reset
  AUTH_RESET_SESSION_INVALID: 'AUTH_RESET_SESSION_INVALID',

  // Validation
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  VALIDATION_REQUIRED: 'VALIDATION_REQUIRED',
  VALIDATION_INVALID_EMAIL: 'VALIDATION_INVALID_EMAIL',
  VALIDATION_INVALID_PHONE: 'VALIDATION_INVALID_PHONE',
  VALIDATION_PASSWORD_WEAK: 'VALIDATION_PASSWORD_WEAK',

  // Account
  ACCOUNT_NOT_FOUND: 'ACCOUNT_NOT_FOUND',
  ACCOUNT_SUSPENDED: 'ACCOUNT_SUSPENDED',
  ACCOUNT_ALREADY_SUSPENDED: 'ACCOUNT_ALREADY_SUSPENDED',
  ACCOUNT_ALREADY_ACTIVE: 'ACCOUNT_ALREADY_ACTIVE',

  // Verification
  VERIFICATION_REASON_REQUIRED: 'VERIFICATION_REASON_REQUIRED',
  VERIFICATION_SELF_APPROVAL_NOT_ALLOWED: 'VERIFICATION_SELF_APPROVAL_NOT_ALLOWED',
  VERIFICATION_QUEUE_ENTRY_MISSING: 'VERIFICATION_QUEUE_ENTRY_MISSING',
  VERIFICATION_ALREADY_COMPLETED: 'VERIFICATION_ALREADY_COMPLETED',

  // Archive
  ARCHIVE_REASON_REQUIRED: 'ARCHIVE_REASON_REQUIRED',

  // Rate Limit
  RATE_LIMIT_EXCEEDED: 'RATE_LIMIT_EXCEEDED',

  // Upload
  UPLOAD_NOT_FOUND: 'UPLOAD_NOT_FOUND',
  UPLOAD_INVALID_TYPE: 'UPLOAD_INVALID_TYPE',
  UPLOAD_TOO_LARGE: 'UPLOAD_TOO_LARGE',
  UPLOAD_ACTIVE: 'UPLOAD_ACTIVE',
  UPLOAD_DELETED: 'UPLOAD_DELETED',
  UPLOAD_INVALID_STATUS: 'UPLOAD_INVALID_STATUS',

  // Profile
  PROFILE_NOT_FOUND: 'PROFILE_NOT_FOUND',
  PROFILE_ALREADY_ACTIVE: 'PROFILE_ALREADY_ACTIVE',
  PROFILE_MISSING_BASIC: 'PROFILE_MISSING_BASIC',
  PROFILE_MISSING_COMMUNITY: 'PROFILE_MISSING_COMMUNITY',
  PROFILE_MISSING_PHOTO: 'PROFILE_MISSING_PHOTO',
  PROFILE_MISSING_DEFAULT_TRANSLATION: 'PROFILE_MISSING_DEFAULT_TRANSLATION',
  PROFILE_ALREADY_SUBMITTED: 'PROFILE_ALREADY_SUBMITTED',
  PROFILE_REJECTED: 'PROFILE_REJECTED',
  PROFILE_WRONG_STATUS: 'PROFILE_WRONG_STATUS',
  PROFILE_NAME_INVALID: 'PROFILE_NAME_INVALID',

  // Shortlist
  SHORTLIST_OWN_PROFILE: 'SHORTLIST_OWN_PROFILE',

  // Membership
  AUTH_INSUFFICIENT_MEMBERSHIP: 'AUTH_INSUFFICIENT_MEMBERSHIP',
  MEMBERSHIP_PLAN_NOT_FOUND: 'MEMBERSHIP_PLAN_NOT_FOUND',
  MEMBERSHIP_PLAN_INACTIVE: 'MEMBERSHIP_PLAN_INACTIVE',
  MEMBERSHIP_QUOTA_EXCEEDED: 'MEMBERSHIP_QUOTA_EXCEEDED',
  MEMBERSHIP_SLOT_LIMIT_REACHED: 'MEMBERSHIP_SLOT_LIMIT_REACHED',
  MEMBERSHIP_SHORTLIST_LIMIT_REACHED: 'MEMBERSHIP_SHORTLIST_LIMIT_REACHED',
  MEMBERSHIP_PREMIUM_REQUIRED: 'MEMBERSHIP_PREMIUM_REQUIRED',
  SUBSCRIPTION_NOT_FOUND: 'SUBSCRIPTION_NOT_FOUND',
  NO_REVERTABLE_SUBSCRIPTION: 'NO_REVERTABLE_SUBSCRIPTION',

  // Mandapam
  MANDAPAM_PACKAGE_NOT_FOUND: 'MANDAPAM_PACKAGE_NOT_FOUND',
  MANDAPAM_PACKAGE_CODE_INVALID: 'MANDAPAM_PACKAGE_CODE_INVALID',
  MANDAPAM_PACKAGE_FUNCTION_NOT_FOUND: 'MANDAPAM_PACKAGE_FUNCTION_NOT_FOUND',
  MANDAPAM_FACILITY_NOT_FOUND: 'MANDAPAM_FACILITY_NOT_FOUND',
  MANDAPAM_ADDON_NOT_FOUND: 'MANDAPAM_ADDON_NOT_FOUND',
  MANDAPAM_IMMUTABLE_FIELD: 'MANDAPAM_IMMUTABLE_FIELD',

  // Mandapam Booking
  MANDAPAM_PACKAGE_INACTIVE: 'MANDAPAM_PACKAGE_INACTIVE',
  MANDAPAM_PACKAGE_NO_PRICING: 'MANDAPAM_PACKAGE_NO_PRICING',
  MANDAPAM_ADDON_INACTIVE: 'MANDAPAM_ADDON_INACTIVE',
  BOOKING_CANCELLED: 'BOOKING_CANCELLED',
  BOOKING_NOT_FOUND: 'BOOKING_NOT_FOUND',
  INVALID_STATUS_TRANSITION: 'INVALID_STATUS_TRANSITION',
  DATE_BLOCKED: 'DATE_BLOCKED',
  DATE_ALREADY_BOOKED: 'DATE_ALREADY_BOOKED',
  DATE_HAS_BOOKINGS: 'DATE_HAS_BOOKINGS',
  DATE_NOT_FOUND: 'DATE_NOT_FOUND',

  // General
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  NOT_FOUND: 'NOT_FOUND',
} as const;
