import { z } from 'zod';

export const createProfileSchema = z.object({
  basic: z.object({
    profileFor: z.string().min(1),
    gender: z.string().min(1),
    dob: z.string().min(1),
    diet: z.string().min(1),
    bloodGroup: z.string().nullable().optional(),
    height: z.number().positive(),
    weight: z.number().nullable().optional(),
    complexion: z.string().nullable().optional(),
    maritalStatus: z.string().nullable().optional(),
    currentDistrict: z.string().nullable().optional(),
    currentTaluk: z.string().nullable().optional(),
    currentCityEn: z.string().nullable().optional(),
    currentCityTa: z.string().nullable().optional(),
    currentStateEn: z.string().nullable().optional(),
    currentStateTa: z.string().nullable().optional(),
    currentCountryEn: z.string().nullable().optional(),
    currentCountryTa: z.string().nullable().optional(),
    nativeDistrict: z.string().nullable().optional(),
    nativeTaluk: z.string().nullable().optional(),
  }),
  community: z.object({
    community: z.string().min(1).optional(),
    communityId: z.number().positive().optional(),
    caste: z.string().min(1).optional(),
    casteId: z.number().positive().optional(),
    kulam: z.string().nullable().optional(),
    kulamId: z.number().nullable().optional(),
  }).refine((d) => d.community || d.communityId, { message: 'community or communityId required' })
    .refine((d) => d.caste || d.casteId, { message: 'caste or casteId required' }),
  professional: z.object({
    education: z.string().nullable().optional(),
    jobSector: z.string().nullable().optional(),
    jobSectorId: z.number().nullable().optional(),
    jobDetail: z.string().nullable().optional(),
    companyName: z.string().nullable().optional(),
    jobLocationEn: z.string().nullable().optional(),
    jobLocationTa: z.string().nullable().optional(),
    monthlySalary: z.number().nullable().optional(),
  }).nullable().optional(),
  family: z.object({
    fatherAlive: z.boolean().optional(),
    fatherName: z.string().nullable().optional(),
    fatherJob: z.string().nullable().optional(),
    fatherSalary: z.number().nullable().optional(),
    motherAlive: z.boolean().optional(),
    motherName: z.string().nullable().optional(),
    motherJob: z.string().nullable().optional(),
    motherSalary: z.number().nullable().optional(),
    noOfBrother: z.number().nullable().optional(),
    noOfSister: z.number().nullable().optional(),
  }).nullable().optional(),
  horoscope: z.object({
    mode: z.string().nullable().optional(),
    birthTime: z.string().nullable().optional(),
    birthPlace: z.string().nullable().optional(),
    rasi: z.string().nullable().optional(),
    nakshatra: z.string().nullable().optional(),
    lagna: z.string().nullable().optional(),
    rasiId: z.number().nullable().optional(),
    nakshatraId: z.number().nullable().optional(),
    lagnaId: z.number().nullable().optional(),
    rasiChartUploadId: z.string().nullable().optional(),
    navamsaChartUploadId: z.string().nullable().optional(),
    horoscopeJson: z.any().nullable().optional(),
  }).nullable().optional(),
  photos: z.object({
    primaryUploadId: z.string().uuid(),
    galleryUploadIds: z.array(z.string()).optional(),
  }),
  assets: z.object({
    landEn: z.string().nullable().optional(),
    landTa: z.string().nullable().optional(),
    residenceType: z.string().nullable().optional(),
    otherAssetsEn: z.string().nullable().optional(),
    otherAssetsTa: z.string().nullable().optional(),
    vehicle: z.string().nullable().optional(),
  }).nullable().optional(),
  partnerPreference: z.object({
    ageMin: z.number().nullable().optional(),
    ageMax: z.number().nullable().optional(),
    heightMinId: z.number().nullable().optional(),
    heightMaxId: z.number().nullable().optional(),
    monthlySalary: z.number().nullable().optional(),
    expectationNoteEn: z.string().nullable().optional(),
    expectationNoteTa: z.string().nullable().optional(),
    preferredLocationEn: z.string().nullable().optional(),
    preferredLocationTa: z.string().nullable().optional(),
  }).nullable().optional(),
  translations: z.array(z.object({
    language: z.enum(['EN', 'TA']),
    firstName: z.string().nullable().optional(),
    lastName: z.string().nullable().optional(),
    kuladeivam: z.string().nullable().optional(),
    fatherName: z.string().nullable().optional(),
    motherName: z.string().nullable().optional(),
    jobLocation: z.string().nullable().optional(),
  })).min(1),
  agreedToTerms: z.literal(true, { errorMap: () => ({ message: 'You must agree to the terms' }) }),
}).refine((doc) => {
  const en = doc.translations.find(t => t.language === 'EN');
  return en && en.firstName && en.firstName.trim().length > 0;
}, { message: 'EN translation with firstName is required' });
