server {
    listen 80;

    location / {
        proxy_pass http://frontend:5173;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /api/ {
        proxy_pass http://backend:4000/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /mohanur_kongu/ {
        alias /media-mohanurkongu/;
        expires 365d;
        add_header Cache-Control "public, immutable";
    }

    location /mohanur_kongu_manamaalai/ {
        alias /storage/media/;
        expires 365d;
        add_header Cache-Control "public, immutable";
    }
}
