import { z } from 'zod';
import { District, Kulam, Nakshatra, Rasi, ProfileFor, Gender, MaritalStatus, Diet, Complexion, JobSector, Residence } from '@prisma/client';

export const profileSchema = z.object({
    profileFor: z.nativeEnum(ProfileFor),
    firstNameEn: z.string().min(2).max(100),
    lastNameEn: z.string().max(100).optional().nullable(),
    firstNameTa: z.string().max(100).optional().nullable(),
    lastNameTa: z.string().max(100).optional().nullable(),
    dob: z.string().or(z.date()).transform((val) => new Date(val)),
    gender: z.nativeEnum(Gender),
    maritalStatus: z.nativeEnum(MaritalStatus).optional().nullable(),
    currentTaluk: z.string().max(100).optional().nullable(),
    currentDistrict: z.nativeEnum(District).optional().nullable(),
    currentDistrictEn: z.string().max(100).optional().nullable(),
    currentDistrictTa: z.string().max(100).optional().nullable(),
    currentCityEn: z.string().max(100).optional().nullable(),
    currentCityTa: z.string().max(100).optional().nullable(),
    currentStateEn: z.string().max(100).optional().nullable(),
    currentStateTa: z.string().max(100).optional().nullable(),
    currentCountryEn: z.string().max(100).optional().nullable(),
    currentCountryTa: z.string().max(100).optional().nullable(),
    nativeTaluk: z.string().max(100).optional().nullable(),
    nativeDistrict: z.nativeEnum(District).optional().nullable(),
    bloodGroup: z.string().max(20).optional().nullable(),
    height: z.number().positive().min(120).max(250).optional().nullable(),
    weight: z.number().positive().min(20).max(250).optional().nullable(),
    diet: z.nativeEnum(Diet).optional().nullable(),
    complexion: z.nativeEnum(Complexion).optional().nullable(),
    caste: z.string().max(100).optional().nullable(),
    community: z.string().max(100).optional().nullable(),
    kulam: z.nativeEnum(Kulam).optional().nullable(),
    kuladeivamEn: z.string().max(100).optional().nullable(),
    kuladeivamTa: z.string().max(100).optional().nullable(),
    star: z.nativeEnum(Nakshatra).optional().nullable(),
    rasi: z.nativeEnum(Rasi).optional().nullable(),
    laganam: z.nativeEnum(Rasi).optional().nullable(),
    dosham: z.string().optional().nullable(), // For now allowing string from frontend options
    birthTime: z.string().max(20).optional().nullable(),
    birthPlace: z.string().max(200).optional().nullable(),
    birthPlaceName: z.string().max(200).optional().nullable(),
    birthLocationName: z.string().max(200).optional().nullable(),
    birthLatitude: z.number().min(-90).max(90).optional().nullable(),
    birthLongitude: z.number().min(-180).max(180).optional().nullable(),
    education: z.string().max(255).optional().nullable(),
    jobDetail: z.string().max(255).optional().nullable(),
    companyName: z.string().max(255).optional().nullable(),
    jobSector: z.nativeEnum(JobSector).optional().nullable(),
    jobLocationEn: z.string().max(255).optional().nullable(),
    jobLocationTa: z.string().max(255).optional().nullable(),
    salaryMonthly: z.number().positive().optional().nullable(),
    fatherNameEn: z.string().max(100).optional().nullable(),
    fatherNameTa: z.string().max(100).optional().nullable(),
    fatherIsLate: z.boolean().optional(),
    fatherJob: z.string().max(100).optional().nullable(),
    fatherSalary: z.number().positive().optional().nullable(),
    motherNameEn: z.string().max(100).optional().nullable(),
    motherNameTa: z.string().max(100).optional().nullable(),
    motherIsLate: z.boolean().optional(),
    motherJob: z.string().max(100).optional().nullable(),
    motherSalary: z.number().positive().optional().nullable(),
    noOfBrothers: z.number().int().min(0).max(20).optional().nullable(),
    noOfSisters: z.number().int().min(0).max(20).optional().nullable(),
    residence: z.nativeEnum(Residence).optional().nullable(),
    propertyDetailsEn: z.string().max(2000).optional().nullable(),
    propertyDetailsTa: z.string().max(2000).optional().nullable(),
    expectationEn: z.string().max(2000).optional().nullable(),
    expectationTa: z.string().max(2000).optional().nullable(),
    gallery: z.array(z.string()).optional(),
    profilePhoto: z.string().optional().nullable(),
    status: z.enum(['ACTIVE', 'INACTIVE', 'DRAFT']).optional(),
    horoscope: z.object({
        mode: z.enum(['CREATE', 'UPLOAD']),
        rasi: z.string().optional().nullable(),
        navamsa: z.string().optional().nullable(),
        rasiPath: z.string().optional().nullable(),
        navamsaPath: z.string().optional().nullable(),
        pdfPath: z.string().optional().nullable(),
        filePath: z.string().optional().nullable(),
        horoscopeVersion: z.number().optional(),
        horoscopeJson: z.any().optional().nullable(),
        birthDate: z.string().optional().nullable(),
        birthTime: z.string().optional().nullable(),
        birthLocationName: z.string().optional().nullable(),
        birthLatitude: z.number().optional().nullable(),
        birthLongitude: z.number().optional().nullable(),
        timezone: z.string().optional().nullable(),
        ayanamsa: z.number().optional().nullable(),
        generationHash: z.string().optional().nullable(),
    }).optional(),
});

export type ProfileInput = z.infer<typeof profileSchema>;
