export const districtToShortCode: Record<string, string> = {
  TIRUVALLUR: 'TVL',
  CHENNAI: 'CHN',
  KANCHEEPURAM: 'KPM',
  VELLORE: 'VEL',
  DHARMAPURI: 'DPI',
  TIRUVANNAMALAI: 'TVM',
  VILLUPPURAM: 'VPM',
  SALEM: 'SLM',
  NAMAKKAL: 'NKL',
  ERODE: 'ERD',
  NILGIRIS: 'NIL',
  COIMBATORE: 'CBE',
  DINDIGUL: 'DGL',
  KARUR: 'KRR',
  THIRUCHIRAPPALLI: 'TRY',
  PERAMBALUR: 'PBL',
  ARIYALUR: 'ARL',
  CUDDALORE: 'CUD',
  NAGAPATTINAM: 'NGP',
  THIRUVARUR: 'TVR',
  THANJAVUR: 'TNJ',
  PUDUKKOTTAI: 'PDK',
  SIVAGANGAI: 'SVG',
  MADURAI: 'MDU',
  THENI: 'TNI',
  VIRUDHUNAGAR: 'VNR',
  RAMANATHAPURAM: 'RMN',
  THOOTHUKKUDI: 'TUT',
  TIRUNELVELI: 'TNV',
  KANYAKUMARI: 'KKI',
  KRISHNAGIRI: 'KGI',
  TIRUPPUR: 'TPR',
  KALLAKURICHI: 'KLC',
  TENKASI: 'TKS',
  CHENGALPATTU: 'CPT',
  THIRUPATHUR: 'TPT',
  RANIPET: 'RNP',
  MAYILADUTHURAI: 'MLD',
  OTHER: 'OTR',
};

export const getDistrictShortCode = (district: string | null | undefined): string => {
  if (!district) return 'OTR';
  return districtToShortCode[district] || 'OTR';
};
