export const MINIMUM_PROFILE_SELECT = {
  id: true,
  regNo: true,
  firstNameEn: true,
  lastNameEn: true,
  firstNameTa: true,
  lastNameTa: true,
  dob: true,
  education: true,
  community: true,
  jobDetail: true,
  currentDistrict: true,
  currentDistrictEn: true,
  currentDistrictTa: true,
  currentCityEn: true,
  currentCityTa: true,
  currentTaluk: true,
  profilePhoto: true,
  userId: true,
  adminVerified: true,
  status: true,
  height: true,
  gender: true,
};
