import type { ProfileDraft } from '../lib/indexeddb';

export function formToDraft(formData: Record<string, unknown>): ProfileDraft {
  return {
    basic: {
      profileFor: formData.profileFor || null,
      gender: formData.gender || null,
      dob: formData.dob || null,
      diet: formData.diet || null,
      bloodGroup: formData.bloodGroup || null,
      height: formData.height ?? null,
      weight: formData.weight ?? null,
      complexion: formData.complexion || null,
      maritalStatus: formData.maritalStatus || null,
      currentDistrict: formData.currentDistrict || null,
      currentTaluk: formData.currentTaluk || null,
      currentCityEn: formData.currentCityEn || null,
      currentCityTa: formData.currentCityTa || null,
      currentStateEn: formData.currentStateEn || null,
      currentStateTa: formData.currentStateTa || null,
      currentCountryEn: formData.currentCountryEn || null,
      currentCountryTa: formData.currentCountryTa || null,
      nativeDistrict: formData.nativeDistrict || null,
      nativeTaluk: formData.nativeTaluk || null,
    },
    community: {
      community: formData.community || null,
      caste: formData.caste || null,
      kulam: formData.kulam || null,
    },
    professional: {
      education: formData.education || null,
      jobSector: formData.jobSector || null,
      jobDetail: formData.jobDetail || null,
      companyName: formData.companyName || null,
      jobLocationEn: formData.jobLocationEn || null,
      jobLocationTa: formData.jobLocationTa || null,
      monthlySalary: formData.monthlySalary ?? null,
    },
    family: {
      fatherAlive: formData.fatherIsLate !== true,
      fatherName: formData.fatherNameEn || null,
      fatherJob: formData.fatherJob || null,
      fatherSalary: formData.fatherSalary ?? null,
      motherAlive: formData.motherIsLate !== true,
      motherName: formData.motherNameEn || null,
      motherJob: formData.motherJob || null,
      motherSalary: formData.motherSalary ?? null,
      noOfBrother: formData.noOfBrothers ?? null,
      noOfSister: formData.noOfSisters ?? null,
    },
    horoscope: {
      mode: (formData as any).astrology?.mode || null,
      birthTime: (formData as any).astrology?.birthTime || null,
      birthPlace: (formData as any).astrology?.birthPlaceName || null,
      birthLat: (formData as any).astrology?.birthLatitude ?? null,
      birthLong: (formData as any).astrology?.birthLongitude ?? null,
      timezone: (formData as any).astrology?.timezone || null,
      ayanamsa: (formData as any).astrology?.ayanamsa || null,
      rasi: formData.rasi || null,
      nakshatra: formData.star || null,
      lagna: formData.laganam || null,
      rasiChartUploadId: (formData as any).astrology?.rasiChartUploadId || null,
      navamsaChartUploadId: (formData as any).astrology?.navamsaChartUploadId || null,
      horoscopeJson: (formData as any).astrology?.horoscopeJson || null,
    },
    photos: {
      primaryUploadId: (formData as any).primaryUploadId || null,
      galleryUploadIds: (formData as any).galleryUploadIds || [],
    },
    assets: {
      landEn: formData.landEn || null,
      landTa: formData.landTa || null,
      residenceType: formData.residence || null,
      otherAssetsEn: formData.otherAssetsEn || null,
      otherAssetsTa: formData.otherAssetsTa || null,
      vehicle: formData.vehicle || null,
    },
    partnerPreference: {
      ageMin: formData.ageMin ?? null,
      ageMax: formData.ageMax ?? null,
      heightMinId: formData.heightMinId ?? null,
      heightMaxId: formData.heightMaxId ?? null,
      monthlySalary: formData.monthlySalary ?? null,
      expectationNoteEn: formData.expectationNoteEn || null,
      expectationNoteTa: formData.expectationNoteTa || null,
      preferredLocationEn: formData.preferredLocationEn || null,
      preferredLocationTa: formData.preferredLocationTa || null,
    },
    translations: [
      {
        language: 'EN',
        firstName: formData.firstNameEn ?? null,
        lastName: formData.lastNameEn ?? null,
        kuladeivam: formData.kuladeivamEn ?? null,
        fatherName: formData.fatherNameEn ?? null,
        motherName: formData.motherNameEn ?? null,
        jobLocation: formData.jobLocationEn ?? null,
      },
      {
        language: 'TA',
        firstName: formData.firstNameTa ?? null,
        lastName: formData.lastNameTa ?? null,
        kuladeivam: formData.kuladeivamTa ?? null,
        fatherName: formData.fatherNameTa ?? null,
        motherName: formData.motherNameTa ?? null,
        jobLocation: formData.jobLocationTa ?? null,
      },
    ],
    updatedAt: Date.now(),
  };
}

export function draftToForm(draft: ProfileDraft): Record<string, unknown> {
  const en = draft.translations.find(t => t.language === 'EN') || {};
  const ta = draft.translations.find(t => t.language === 'TA') || {};

  return {
    ...draft.basic,
    ...draft.community,
    ...draft.professional,
    ...draft.family,
    ...draft.assets,
    ...draft.partnerPreference,
    firstNameEn: en.firstName || null,
    lastNameEn: en.lastName || null,
    kuladeivamEn: en.kuladeivam || null,
    fatherNameEn: en.fatherName || null,
    motherNameEn: en.motherName || null,
    jobLocationEn: en.jobLocation || null,
    firstNameTa: ta.firstName || null,
    lastNameTa: ta.lastName || null,
    kuladeivamTa: ta.kuladeivam || null,
    fatherNameTa: ta.fatherName || null,
    motherNameTa: ta.motherName || null,
    jobLocationTa: ta.jobLocation || null,
    fatherIsLate: !draft.family.fatherAlive,
    motherIsLate: !draft.family.motherAlive,
    noOfBrothers: draft.family.noOfBrother,
    noOfSisters: draft.family.noOfSister,
    residence: draft.assets.residenceType,
    primaryUploadId: draft.photos.primaryUploadId,
    galleryUploadIds: draft.photos.galleryUploadIds,
    astrology: {
      mode: draft.horoscope.mode,
      birthTime: draft.horoscope.birthTime,
      birthPlaceName: draft.horoscope.birthPlace,
      birthLatitude: draft.horoscope.birthLat,
      birthLongitude: draft.horoscope.birthLong,
      timezone: draft.horoscope.timezone,
      ayanamsa: draft.horoscope.ayanamsa,
      rasiChartUploadId: draft.horoscope.rasiChartUploadId,
      navamsaChartUploadId: draft.horoscope.navamsaChartUploadId,
      horoscopeJson: draft.horoscope.horoscopeJson,
    },
    rasi: draft.horoscope.rasi,
    star: draft.horoscope.nakshatra,
    laganam: draft.horoscope.lagna,
  };
}
