import type { ProfileDraft } from '../lib/indexeddb';

export function formToDraft(formData: Record<string, unknown>): ProfileDraft {
  return {
    profileId: formData.profileId as string | undefined,
    basic: {
      profileFor: formData.profileFor || null,
      gender: formData.gender || null,
      dob: formData.dob || null,
      diet: formData.diet || null,
      bloodGroup: formData.bloodGroup || null,
      height: formData.height ?? null,
      weight: formData.weight ?? null,
      complexion: formData.complexion || null,
      maritalStatus: formData.maritalStatus || null,
      currentDistrict: formData.currentDistrict || null,
      currentTaluk: formData.currentTaluk || null,
      currentCityEn: formData.currentCityEn || null,
      currentCityTa: formData.currentCityTa || null,
      currentStateEn: formData.currentStateEn || null,
      currentStateTa: formData.currentStateTa || null,
      currentCountryEn: formData.currentCountryEn || null,
      currentCountryTa: formData.currentCountryTa || null,
      nativeDistrict: formData.nativeDistrict || null,
      nativeTaluk: formData.nativeTaluk || null,
      nativeCityEn: formData.nativeCityEn || null,
      nativeCityTa: formData.nativeCityTa || null,
      nativeStateEn: formData.nativeStateEn || null,
      nativeStateTa: formData.nativeStateTa || null,
      nativeCountryEn: formData.nativeCountryEn || null,
      nativeCountryTa: formData.nativeCountryTa || null,
    },
    community: {
      community: formData.community || null,
      caste: formData.caste || null,
      kulam: formData.kulam || null,
    },
    professional: {
      education: formData.education || null,
      jobSector: formData.jobSector || null,
      jobDetail: formData.jobDetail || null,
      companyName: formData.companyName || null,
      jobLocationEn: formData.jobLocationEn || null,
      jobLocationTa: formData.jobLocationTa || null,
      monthlySalary: formData.salaryMonthly ?? null,
    },
    family: {
      fatherAlive: formData.fatherIsLate !== true,
      fatherName: formData.fatherNameEn || null,
      fatherJob: formData.fatherJob || null,
      fatherSalary: formData.fatherSalary ?? null,
      motherAlive: formData.motherIsLate !== true,
      motherName: formData.motherNameEn || null,
      motherJob: formData.motherJob || null,
      motherSalary: formData.motherSalary ?? null,
      noOfBrother: formData.noOfBrothers ?? null,
      noOfSister: formData.noOfSisters ?? null,
    },
    horoscope: {
      mode: (formData as any).astrology?.mode || null,
      rasi: formData.rasi || null,
      nakshatra: formData.star || null,
      lagna: formData.laganam || null,
      rasiChartUploadId: (formData as any).astrology?.rasiChartUploadId || null,
      navamsaChartUploadId: (formData as any).astrology?.navamsaChartUploadId || null,
      horoscopeJson: (formData as any).astrology?.horoscopeJson || null,
    },
    photos: {
      primaryUploadId: (formData as any).primaryUploadId || null,
      galleryUploadIds: (formData as any).galleryUploadIds || [],
    },
    assets: {
      landEn: formData.landEn || null,
      landTa: formData.landTa || null,
      residenceType: formData.residence === 'OWN_HOUSE' ? 'OWNED' : (formData.residence || null),
      otherAssetsEn: formData.otherAssetsEn || null,
      otherAssetsTa: formData.otherAssetsTa || null,
      vehicle: formData.vehicle || null,
    },
    partnerPreference: {
      ageMin: formData.ageMin ?? null,
      ageMax: formData.ageMax ?? null,
      heightMinId: formData.heightMinId ?? null,
      heightMaxId: formData.heightMaxId ?? null,
      monthlySalary: formData.monthlySalary ?? null,
      expectationNoteEn: formData.expectationNoteEn || null,
      expectationNoteTa: formData.expectationNoteTa || null,
      preferredLocationEn: formData.preferredLocationEn || null,
      preferredLocationTa: formData.preferredLocationTa || null,
    },
    translations: [
      {
        language: 'EN',
        firstName: formData.firstNameEn ?? null,
        lastName: formData.lastNameEn ?? null,
        kuladeivam: formData.kuladeivamEn ?? null,
        fatherName: formData.fatherNameEn ?? null,
        motherName: formData.motherNameEn ?? null,
        jobLocation: formData.jobLocationEn ?? null,
      },
      {
        language: 'TA',
        firstName: formData.firstNameTa ?? null,
        lastName: formData.lastNameTa ?? null,
        kuladeivam: formData.kuladeivamTa ?? null,
        fatherName: formData.fatherNameTa ?? null,
        motherName: formData.motherNameTa ?? null,
        jobLocation: formData.jobLocationTa ?? null,
      },
    ],
    updatedAt: Date.now(),
  };
}

export function draftToForm(draft: Partial<ProfileDraft>): Record<string, unknown> {
  const en = (draft.translations || []).find(t => t.language === 'EN') || {};
  const ta = (draft.translations || []).find(t => t.language === 'TA') || {};

  return {
    ...(draft.basic || {}),
    ...(draft.community || {}),
    ...(draft.professional || {}),
    ...(draft.family || {}),
    ...(draft.assets || {}),
    ...(draft.partnerPreference || {}),
    firstNameEn: en.firstName || null,
    lastNameEn: en.lastName || null,
    kuladeivamEn: en.kuladeivam || null,
    fatherNameEn: en.fatherName || null,
    motherNameEn: en.motherName || null,
    jobLocationEn: en.jobLocation || null,
    firstNameTa: ta.firstName || null,
    lastNameTa: ta.lastName || null,
    kuladeivamTa: ta.kuladeivam || null,
    fatherNameTa: ta.fatherName || null,
    motherNameTa: ta.motherName || null,
    jobLocationTa: ta.jobLocation || null,
    salaryMonthly: draft.professional?.monthlySalary ?? null,
    fatherIsLate: !draft.family?.fatherAlive,
    motherIsLate: !draft.family?.motherAlive,
    noOfBrothers: draft.family?.noOfBrother ?? null,
    noOfSisters: draft.family?.noOfSister ?? null,
    residence: draft.assets?.residenceType === 'OWNED' ? 'OWN_HOUSE' : (draft.assets?.residenceType ?? null),
    primaryUploadId: draft.photos?.primaryUploadId ?? null,
    galleryUploadIds: draft.photos?.galleryUploadIds ?? [],
    astrology: {
      mode: draft.horoscope?.mode ?? null,
      rasiChartUploadId: draft.horoscope?.rasiChartUploadId ?? null,
      navamsaChartUploadId: draft.horoscope?.navamsaChartUploadId ?? null,
      horoscopeJson: draft.horoscope?.horoscopeJson ?? null,
    },
    rasi: draft.horoscope?.rasi ?? null,
    star: draft.horoscope?.nakshatra ?? null,
    laganam: draft.horoscope?.lagna ?? null,
  };
}
